variables:
  APP_NAME: "read-log"
  MAJOR_VERSION: "0"
  MINOR_VERSION: "6"
  MAINTENANCE_VERSION: "4"
  INSPECTION_ENABLED: 'false'
  TEST_ENABLED: 'false'
  ARTIFACTORY_PUBLISH: 'false'
  
include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-java.yml'
